services:
  linux-amd64:
    build:
      context: ./docker/linux
    image: fyne-cross-custom:linux-amd64
    platform: linux/amd64
    x-bake:
      tags:
        - fyne-cross-custom:linux-amd64
      output: type=docker
      pull: false
  linux-arm:
    build:
      context: ./docker/linux
    image: fyne-cross-custom:linux-arm64
    platform: linux/arm64
    x-bake:
      tags:
        - fyne-cross-custom:linux-arm64
      output: type=docker
      platforms:
        - linux/arm64
      pull: false
  linuxgo-arm:
    build:
      context: ./docker/linux-new
    image: brainser-linuxgo:arm64
    platform: linux/arm64
    x-bake:
      tags:
        - brainser-linuxgo:arm64
      output: type=docker
      platforms:
        - linux/arm64
      pull: false
  linuxgo-amd64:
    build:
      context: ./docker/linux-new
    image: brainser-linuxgo:amd64
    platform: linux/amd64
    x-bake:
      tags:
        - brainser-linuxgo:amd64
      output: type=docker
      platforms:
        - linux/amd64
      pull: false